### ISSUE TITLE
point of order: amendments and transmutabiltiy require rule number changes

### ISSUE THREAD

**Issue by mburns** [mburns/nomic#28]
# What

As I (now) read rule 108, transmuting or modifying a rule requires that we assign it a new `3xx` rule number, for purposes of assigning points (and aiding in versioning the rules themselves).
# Corrections
- [x] #12 should represent proposal `302` (failed)
- [ ] #14 should have renumbered `105` -> `303`
- [x] #15 should have been numbered `304` originally
- [ ] #22 should renumber (formerly rule `105`) `303` -> `305`
- [x] #23 should renumber `201` -> `306`
- [x] #27 should renumber `207` -> `307`
- [x] #30 should renumber `203` -> `308`
- [x] #31 should renumber `305` -> `309`
