### ISSUE TITLE
bot software to track votes and score

### ISSUE THREAD

**Issue by mburns** [mburns/nomic#9]
| Terms | Definition |
| --- | --- |
| Player | A Github user that has forked this repo |
| Vote | a comment that contains `/(+|-)1/` _and_ the commenter is an active Player |
| Abstain | a comment that is not specifically a for/against vote (doesn't contain `/(+|-)1/`) by an active Player |
| Quorum | >=`N`% of active Players having Voted. _`N` is currently `100`._ |
## Pull Requests

When Quorum is reached, 
- [ ] tally the votes and post a **comment** with {`total for`, `total against`, `% for`, `% against`, `winning side`, etc}
  - Abstaining from a vote would be a comment from an active Player that doesn't include `/(+|-)1/`
- [ ] close the PR to further comments
- [ ] Determine points to reward Players & update `SCOREBOARD.rb`.
  - Users with `0` points don't need to be listed.

**Comment by mburns** [comment]
https://github.com/jirwin/treslek-github seems like a good place to start.

**Comment by jirwin** [comment]
Should votes be reset when the PR gets a comment?

**Comment by mburns** [comment]
The votes should only have an effect when the PR reaches quorum. Computing the vote's whole score from scratch on each new comment would work.

An active player should be allowed to comment on a PR multiple times, but only have one vote (their last one cast chronologically?)

Scores don't change until a vote is completed (and thus, commenting is locked and votes are tallied).

**Comment by jirwin** [comment]
Let me try and explain the situation I'm concerned with:

3 active players: 1, 2, 3

Player 1 submits a proposal.
Player 2 votes +1.
Player 3 leaves a comment suggesting an edit that would make it +1 for them.
Player 1 agrees and updates the rule.
Player 3 votes +1.

At this point every player has voted(assuming the author gets an automatic +1), but Player 2 has voted +1 for a different rule.

My thought is that after each time the sha1 changes(commit, force push), the quorum counter should be reset so that we know every user has voted on the most recent version of the proposal.

**Comment by mburns** [comment]
Oh wow, you're absolutely right. Rebasing or committing over top the original file should nullify previous votes. So ya, we should recompute.

I can also imagine it getting tricky to read top-to-bottom if there are commit edit mid-way though voting. We should encourage meta discussion be separate comments from votes, so that they don't get intermixed too much.

**Comment by jirwin** [comment]
> I can also imagine it getting tricky to read top-to-bottom if there are commit edit mid-way though voting. We should encourage meta discussion be separate comments from votes, so that they don't get intermixed too much.

To this point, I think we should make votes be _only_ `/(+|-)1/`. Anything else makes it doesn't count as a vote.

**Comment by mburns** [comment]
+1

**Comment by jirwin** [comment]
https://github.com/jirwin/treslek-nomic

Currently this will get the active players, and parse the scores.

# TODO
- [ ] Update scoreboard
- [ ] Track votes within a PR
- [ ] Lock a PR once a vote has completed

**Comment by mburns** [comment]
possible inspiration:
- https://github.com/botwillacceptanything/botwillacceptanything/pull/507
